my_nations:
- Angola
- Botswana
- Chad
- Congo
- Denmark
- Estonia
- Finland
- Germany
- Iceland
- Kenya
- Libya
- Lithuania
- Madagascar
- Malawi
- Mozambique
- Namibia
- Norway
- Poland
- Republic of the Congo
- Rwanda-Burundi
- Somalia
- South Sudan
- Sudan
- Sweden
- Tanzania
- Uganda
- Zambia
