my_nations:
- Benin
- Botswana
- Bulgaria
- Central African Cooperative
- Croatia
- East African Federation
- Germany
- Great Bantu Free State
- Haiti
- Hungary
- Kosovo
- Libya
- Lithuania
- Madagascar
- Micronesian States
- Namibia
- Nordic Federation
- Poland
- Portugal
- Republic of the Congo
- Seychelles
- Sierra Leone
- Slovenia
- Spain
- Sudan
- Switzerland
- Togo
- Tunisia
