my_nations:
- Belarus
- Benin
- Botswana
- Central African Cooperative
- East African Federation
- Egypt
- European Union
- Gabon
- Great Bantu Free State
- Ireland
- Libya
- Madagascar
- Namibia
- Romania
- Russia
- Sierra Leone
- Sudan
- Switzerland
- Togo
- Tunisia
